// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBG3weul8Vp9_iFYBy8D7KMMOeckjQYgY',
    appId: '1:354626426873:web:ceb0cccc546b2538548f28',
    messagingSenderId: '354626426873',
    projectId: 'ogretmentalepleri-3b375',
    authDomain: 'ogretmentalepleri-3b375.firebaseapp.com',
    storageBucket: 'ogretmentalepleri-3b375.appspot.com',
    measurementId: 'G-V1RDC5QXE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEFaZ7aU3S1Z-xpwzytbdS5tr0ogjzBUQ',
    appId: '1:354626426873:android:ef79585d890980b7548f28',
    messagingSenderId: '354626426873',
    projectId: 'ogretmentalepleri-3b375',
    storageBucket: 'ogretmentalepleri-3b375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPSi_rV5n4RPaW3Ye6Id_BpAdGCGeURA',
    appId: '1:354626426873:ios:1e483e2bf1df08b0548f28',
    messagingSenderId: '354626426873',
    projectId: 'ogretmentalepleri-3b375',
    storageBucket: 'ogretmentalepleri-3b375.appspot.com',
    iosClientId: '354626426873-ru7sjf94tnnvno5is0gm8k1e9q7kbs6g.apps.googleusercontent.com',
    iosBundleId: 'com.ogretmentalepleri.ogretmentalepleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPSi_rV5n4RPaW3Ye6Id_BpAdGCGeURA',
    appId: '1:354626426873:ios:8d5c922f177488a8548f28',
    messagingSenderId: '354626426873',
    projectId: 'ogretmentalepleri-3b375',
    storageBucket: 'ogretmentalepleri-3b375.appspot.com',
    iosClientId: '354626426873-2a80al8g2ci0f0vvlku7hfgo1th86i26.apps.googleusercontent.com',
    iosBundleId: 'com.ogretmentalepleri.ogretmentalepleri.RunnerTests',
  );
}
